[package]
name = "DiscordBot"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-openai = { version = "0.32.3", features = ["full"] }
chrono = "0.4.43"
config = "0.15.19"
dialoguer = "0.12.0"
dotenvy = "0.15.7"
indicatif = "0.18.3"
owo-colors = "4.2.3"
poise = "0.6.1"
serde = { version = "1.0.228", features = ["derive"] }
serenity = { version = "0.12.5", features = ["full"] }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-indicatif = "0.3.14"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt"] }