[package]
name = "neko_ai"
version = "0.0.2-alpha"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
config = "0.15.19"
dotenvy = "0.15.7"
poise = "0.6.1"
serenity = { version = "0.12.5", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt"] }